-- Create the main table for meter data
CREATE TABLE IF NOT EXISTS meter_data (
    time        TIMESTAMPTZ       NOT NULL,
--    unique_id TEXT,
--    smr_version DOUBLE PRECISION,
--    meter_model TEXT,
--    wifi_ssid TEXT,
--    wifi_strength DOUBLE PRECISION,
    total_power_import_kwh DOUBLE PRECISION,
--    total_power_import_t1_kwh DOUBLE PRECISION,
--    total_power_import_t2_kwh DOUBLE PRECISION,
--    total_power_import_t3_kwh DOUBLE PRECISION,
--    total_power_import_t4_kwh DOUBLE PRECISION,
    total_power_export_kwh DOUBLE PRECISION,
--    total_power_export_t1_kwh DOUBLE PRECISION,
--    total_power_export_t2_kwh DOUBLE PRECISION,
--    total_power_export_t3_kwh DOUBLE PRECISION,
--    total_power_export_t4_kwh DOUBLE PRECISION,
    active_power_w DOUBLE PRECISION,
    active_power_l1_w DOUBLE PRECISION,
    active_power_l2_w DOUBLE PRECISION,
    active_power_l3_w DOUBLE PRECISION,
    active_voltage_l1_v DOUBLE PRECISION,
    active_voltage_l2_v DOUBLE PRECISION,
    active_voltage_l3_v DOUBLE PRECISION,
    active_current_l1_a DOUBLE PRECISION,
    active_current_l2_a DOUBLE PRECISION,
    active_current_l3_a DOUBLE PRECISION,
    active_frequency_hz DOUBLE PRECISION,
--    voltage_sag_l1_count DOUBLE PRECISION,
--    voltage_sag_l2_count DOUBLE PRECISION,
--    voltage_sag_l3_count DOUBLE PRECISION,
--    voltage_swell_l1_count DOUBLE PRECISION,
--    voltage_swell_l3_count DOUBLE PRECISION,
--    voltage_swell_l2_count DOUBLE PRECISION,
--    any_power_fail_count DOUBLE PRECISION,
--    long_power_fail_count DOUBLE PRECISION,
--    active_power_average_w DOUBLE PRECISION,
--    montly_power_peak_w DOUBLE PRECISION,
--    montly_power_peak_timestamp DOUBLE PRECISION,
--    total_gas_m3 DOUBLE PRECISION,
--    gas_timestamp DOUBLE PRECISION,
--    unique_gas_id DOUBLE PRECISION,
--    external JSONB,
    PRIMARY KEY (time)
);

-- Convert the table to a hypertable
SELECT create_hypertable('meter_data', 'time', if_not_exists => TRUE);